version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Dependencies
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          name: Cache Dependencies
          paths:
            - ~/.cache/yarn
            - node_modules
            - ./JavaScript/eslint-config-hzdg/node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:10.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Dependencies
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run Tests
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
